version: '3'
services:

  # SFTP Server
  sftp-server:
    image: atmoz/sftp
    ports:
      - "2222:22"  # กำหนดพอร์ตที่จะใช้ในการเชื่อมต่อ SFTP (ใช้พอร์ต 2222)
    volumes:
      # Data directory
      - ./sftp-server/data:/home/sftpuser/upload
      
      # SSH host keys (เพื่อให้ fingerprint ไม่เปลี่ยน)
      - ./sftp-server/config/keys/ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./sftp-server/config/keys/ssh_host_rsa_key.pub:/etc/ssh/ssh_host_rsa_key.pub:ro
      - ./sftp-server/config/keys/ssh_host_ecdsa_key:/etc/ssh/ssh_host_ecdsa_key:ro
      - ./sftp-server/config/keys/ssh_host_ecdsa_key.pub:/etc/ssh/ssh_host_ecdsa_key.pub:ro
      - ./sftp-server/config/keys/ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./sftp-server/config/keys/ssh_host_ed25519_key.pub:/etc/ssh/ssh_host_ed25519_key.pub:ro
      
      # User authorized keys
      - ./sftp-server/config/keys/authorized_keys:/home/sftpuser/.ssh/authorized_keys:ro

      # Logs
      - ./sftp-server/logs:/var/log
    command: sftpuser:mypassword:1001:100:upload
    restart: unless-stopped
    environment:
      - SFTP_USERS=sftpuser:mypassword:1001:100:upload
    networks:
      - app-network

  # Kafka
  kafka:
    image: 'bitnami/kafka:3.8.0'
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app-network

  # Kafka Console UI
  console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    environment:
      KAFKA_BROKERS: kafka:9092
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - app-network

  # MySQL Database
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myapp
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Redis Server
  redis-server:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass myredispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "myredispassword", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/db
    networks:
      - app-network
    depends_on:
      redis-server:
        condition: service_healthy
        
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    # volumes:
      # - ./config:/etc/loki
    networks:
      - app-network

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /Users/jack/log/app:/var/log/app   # <-- mount log directory ของคุณ
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - app-network
      
  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"  # Web UI port
      - "1025:1025"  # SMTP port
    restart: unless-stopped
    networks:
      - app-network

# ประกาศ external network
networks:
  app-network:
    external: true  # บอกว่าเป็น external network


volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  redisinsight_data:
    driver: local