version: '3'

services:
  kafka:
    image: bitnami/kafka:3.6.1-debian-11-r0
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"  # Internal Kafka communication
    environment:
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=SASL_SSL://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,SASL_SSL:SASL_SSL
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=SASL_SSL
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=SCRAM-SHA-512
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=SCRAM-SHA-512
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - KAFKA_CFG_SUPER_USERS=User:admin
      - KAFKA_CLIENT_USERS=admin
      - KAFKA_CLIENT_PASSWORDS=admin-secret
      - KAFKA_CFG_SSL_KEYSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.keystore.jks
      - KAFKA_CFG_SSL_KEYSTORE_PASSWORD=keystore_password
      - KAFKA_CFG_SSL_KEY_PASSWORD=keystore_password
      - KAFKA_CFG_SSL_TRUSTSTORE_LOCATION=/bitnami/kafka/config/certs/kafka.truststore.jks
      - KAFKA_CFG_SSL_TRUSTSTORE_PASSWORD=truststore_password
      - KAFKA_OPTS=-Djava.security.auth.login.config=/opt/bitnami/kafka/config/kafka_jaas.conf
    volumes:
      - ./kafka_jaas.conf:/opt/bitnami/kafka/config/kafka_jaas.conf
      - ./certs:/bitnami/kafka/config/certs
    networks:
      - kafka_network

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.7.2
    environment:
      KAFKA_BROKERS: "kafka:9092"
      SCHEMAREGISTRY_ENABLED: "false"
      KAFKA_SASL_ENABLED: "true"
      KAFKA_SASL_MECHANISM: "SCRAM-SHA-512"
      KAFKA_SASL_USERNAME: "admin"
      KAFKA_SASL_PASSWORD: "admin-secret"
      KAFKA_TLS_ENABLED: "true"
      KAFKA_TLS_INSECURE_SKIP_TLS_VERIFY: "true"
      KAFKA_TLS_CAFILE: /etc/certs/ca.crt
      SSL_CERT_FILE: /etc/certs/ca.crt
    ports:
      - "8080:8080"
    volumes:
      - ./certs:/etc/certs:ro
    networks:
      - kafka_network
    depends_on:
      - kafka

networks:
  kafka_network:
