version: '2'

services: 
  postgres_db:
    image: 'postgres:13.1-alpine'
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
