server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: my-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: my-app
          __path__: /var/log/app/*.log   # <-- Promtail จะอ่าน log file ทั้งหมดใน ./logs/*.log
    pipeline_stages:
      - json:
          expressions:
            service: service
            traceId: traceId
            message: message
            level: level
      - labels:
          service:
          traceId:
          message:
          level:
