version: "3.8"

services:
  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    # command: -config.file=/etc/loki/local-config.yaml
    # volumes:
      # - ./config:/etc/loki

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - ./config/promtail-config.yml:/etc/promtail/promtail-config.yml
      - /Users/jack/log/app:/var/log/app   # <-- mount log directory ของคุณ
    command: -config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
