version: '2.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    mem_limit: 512m
    ports:
      - "2181:2181"
    environment:
      # - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    restart: always
    mem_limit: 512m
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      # - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper